def get_reactive_repository_template() -> str:
    return (
        "import 'dart:async';\n"
        "\n"
        "sealed class RepoEvent<T> {}\n"
        "\n"
        "final class RepoItemCreated<T> extends RepoEvent<T> {\n"
        "  final T item;\n"
        "  RepoItemCreated(this.item);\n"
        "}\n"
        "\n"
        "final class RepoItemUpdated<T> extends RepoEvent<T> {\n"
        "  final T item;\n"
        "  RepoItemUpdated(this.item);\n"
        "}\n"
        "\n"
        "final class RepoItemDeleted<T> extends RepoEvent<T> {\n"
        "  final T item;\n"
        "  RepoItemDeleted(this.item);\n"
        "}\n"
        "\n"
        "mixin ReactiveRepository<T> {\n"
        "  final _controller = StreamController<RepoEvent<T>>.broadcast();\n"
        "\n"
        "  Stream<RepoEvent<T>> get eventStream => _controller.stream;\n"
        "\n"
        "  void notifyItemCreated(T item) {\n"
        "    if (!_controller.isClosed) _controller.sink.add(RepoItemCreated(item));\n"
        "  }\n"
        "\n"
        "  void notifyItemUpdated(T item) {\n"
        "    if (!_controller.isClosed) _controller.sink.add(RepoItemUpdated(item));\n"
        "  }\n"
        "\n"
        "  void notifyItemDeleted(T item) {\n"
        "    if (!_controller.isClosed) _controller.sink.add(RepoItemDeleted(item));\n"
        "  }\n"
        "\n"
        "  void disposeReactiveRepo() => _controller.close();\n"
        "}\n"
    )
