def get_list_response_template() -> str:
    return (
        "class ListResponse<T> {\n"
        "  final List<T> data;\n"
        "  final int total;\n"
        "  final int page;\n"
        "  final int pageSize;\n"
        "\n"
        "  ListResponse({\n"
        "    required this.data,\n"
        "    required this.total,\n"
        "    required this.page,\n"
        "    required this.pageSize,\n"
        "  });\n"
        "\n"
        "  factory ListResponse.fromJson(\n"
        "    Map<String, dynamic> json,\n"
        "    T Function(Map<String, dynamic>) fromJsonT,\n"
        "  ) {\n"
        "    final items = (json['data'] as List<dynamic>?)\n"
        "            ?.map((item) => fromJsonT(item as Map<String, dynamic>))\n"
        "            .toList() ??\n"
        "        [];\n"
        "\n"
        "    return ListResponse(\n"
        "      data: items,\n"
        "      total: json['total'] as int? ?? items.length,\n"
        "      page: json['page'] as int? ?? 1,\n"
        "      pageSize: json['page_size'] as int? ?? items.length,\n"
        "    );\n"
        "  }\n"
        "}\n"
    )
