def get_http_service_template() -> str:
    return (
        "import 'dart:convert';\n"
        "\n"
        "import 'package:flutter/services.dart';\n"
        "import 'package:http/http.dart' as http;\n"
        "import 'package:http_parser/http_parser.dart';\n"
        "\n"
        "import 'exceptions/http_exceptions.dart';\n"
        "\n"
        "mixin HttpService {\n"
        "  Future<Map<String, dynamic>> getQuery(Uri url, {Map<String, String>? headers}) async {\n"
        "    late http.Response response;\n"
        "\n"
        "    try {\n"
        "      response = await http.get(url, headers: headers);\n"
        "    } catch (error) {\n"
        "      throw NoInternetException({\"message\": error.toString()});\n"
        "    }\n"
        "\n"
        "    final utf8Body = utf8.decode(response.bodyBytes);\n"
        "    final body = jsonDecode(utf8Body) as Map<String, dynamic>;\n"
        "\n"
        "    _processStatusCode(response.statusCode, body);\n"
        "\n"
        "    return body;\n"
        "  }\n"
        "\n"
        "  Future<Map<String, dynamic>> postQuery(Uri url, Map<String, dynamic> body, {Map<String, String>? headers}) async {\n"
        "    final jsonEncoded = jsonEncode(body);\n"
        "    final contentType = {'Content-Type': 'application/json'};\n"
        "\n"
        "    final applicationHeaders = {...contentType, ...headers ?? {}};\n"
        "\n"
        "    late http.Response response;\n"
        "\n"
        "    try {\n"
        "      response = await http.post(url, body: jsonEncoded, headers: applicationHeaders);\n"
        "    } catch (error) {\n"
        "      throw NoInternetException({\"message\": error.toString()});\n"
        "    }\n"
        "\n"
        "    final utf8Body = utf8.decode(response.bodyBytes);\n"
        "    final decodedBody = jsonDecode(utf8Body) as Map<String, dynamic>;\n"
        "\n"
        "    _processStatusCode(response.statusCode, decodedBody);\n"
        "\n"
        "    return decodedBody;\n"
        "  }\n"
        "\n"
        "  Future<Map<String, dynamic>> putQuery(Uri url, Map<String, dynamic> body, {Map<String, String>? headers}) async {\n"
        "    final jsonEncoded = jsonEncode(body);\n"
        "    final contentType = {'Content-Type': 'application/json'};\n"
        "\n"
        "    final applicationHeaders = {...contentType, ...headers ?? {}};\n"
        "\n"
        "    late http.Response response;\n"
        "\n"
        "    try {\n"
        "      response = await http.put(url, body: jsonEncoded, headers: applicationHeaders);\n"
        "    } catch (error) {\n"
        "      throw NoInternetException({\"message\": error.toString()});\n"
        "    }\n"
        "\n"
        "    final utf8Body = utf8.decode(response.bodyBytes);\n"
        "    final decodedBody = jsonDecode(utf8Body) as Map<String, dynamic>;\n"
        "\n"
        "    _processStatusCode(response.statusCode, decodedBody);\n"
        "\n"
        "    return decodedBody;\n"
        "  }\n"
        "\n"
        "  Future<Map<String, dynamic>> patchQuery(Uri url, {Map<String, dynamic>? body, Map<String, String>? headers}) async {\n"
        "    String? jsonEncoded;\n"
        "    if (body != null) jsonEncoded = jsonEncode(body);\n"
        "\n"
        "    final contentType = {'Content-Type': 'application/json'};\n"
        "    final applicationHeaders = {...contentType, ...headers ?? {}};\n"
        "\n"
        "    late http.Response response;\n"
        "\n"
        "    try {\n"
        "      response = await http.patch(url, body: jsonEncoded, headers: applicationHeaders);\n"
        "    } catch (error) {\n"
        "      throw NoInternetException({\"message\": error.toString()});\n"
        "    }\n"
        "\n"
        "    final utf8Body = utf8.decode(response.bodyBytes);\n"
        "    final decodedBody = jsonDecode(utf8Body) as Map<String, dynamic>;\n"
        "\n"
        "    _processStatusCode(response.statusCode, decodedBody);\n"
        "\n"
        "    return decodedBody;\n"
        "  }\n"
        "\n"
        "  Future<Map<String, dynamic>> deleteQuery(Uri url, {Map<String, String>? headers}) async {\n"
        "    late http.Response response;\n"
        "\n"
        "    try {\n"
        "      response = await http.delete(url, headers: headers);\n"
        "    } catch (error) {\n"
        "      throw NoInternetException({\"message\": error.toString()});\n"
        "    }\n"
        "\n"
        "    final utf8Body = utf8.decode(response.bodyBytes);\n"
        "    final decodedBody = jsonDecode(utf8Body) as Map<String, dynamic>;\n"
        "\n"
        "    _processStatusCode(response.statusCode, decodedBody);\n"
        "\n"
        "    return decodedBody;\n"
        "  }\n"
        "\n"
        "  Future<Map<String, dynamic>> multipartQuery(\n"
        "    Uri url,\n"
        "    Uint8List bytes, {\n"
        "    String fileName = \"\",\n"
        "    String mediaType = \"image/jpeg\",\n"
        "    Map<String, String>? headers,\n"
        "  }) async {\n"
        "    final request = http.MultipartRequest(\"POST\", url);\n"
        "\n"
        "    if (headers != null) {\n"
        "      request.headers.addAll(headers);\n"
        "    }\n"
        "\n"
        "    request.files.add(\n"
        "      http.MultipartFile.fromBytes(\"file\", bytes, filename: fileName, contentType: MediaType.parse(mediaType)),\n"
        "    );\n"
        "\n"
        "    late http.Response response;\n"
        "\n"
        "    try {\n"
        "      final bytesRequest = await request.send();\n"
        "      response = await http.Response.fromStream(bytesRequest);\n"
        "    } catch (error) {\n"
        "      throw NoInternetException({\"message\": error.toString()});\n"
        "    }\n"
        "\n"
        "    final utf8Body = utf8.decode(response.bodyBytes);\n"
        "    final content = jsonDecode(utf8Body) as Map<String, dynamic>;\n"
        "\n"
        "    _processStatusCode(response.statusCode, content);\n"
        "\n"
        "    return content;\n"
        "  }\n"
        "\n"
        "  void _processStatusCode(int statusCode, Map<String, dynamic> body) {\n"
        "    if (statusCode >= 500) {\n"
        "      throw ServerException(body);\n"
        "    }\n"
        "\n"
        "    if (statusCode == 401) {\n"
        "      throw UnauthorizedException(body);\n"
        "    }\n"
        "\n"
        "    if (statusCode == 403) {\n"
        "      throw ForbiddenException(body);\n"
        "    }\n"
        "\n"
        "    if (statusCode >= 400) {\n"
        "      throw BadRequestException(body, statusCode);\n"
        "    }\n"
        "  }\n"
        "}\n"
    )


def get_http_exceptions_template() -> str:
    return (
        "sealed class HttpServiceException implements Exception {\n"
        "  HttpServiceException(this.message, this.body);\n"
        "  final String message;\n"
        "  final Map<String, dynamic> body;\n"
        "\n"
        "  @override\n"
        "  String toString() {\n"
        "    const prefix = \"HttpServiceException: \";\n"
        "\n"
        "    if (this is! InternalRequestException && body.containsKey(\"detail\")) {\n"
        "      return prefix + body[\"detail\"].toString();\n"
        "    }\n"
        "\n"
        "    return prefix + message;\n"
        "  }\n"
        "}\n"
        "\n"
        "class NoInternetException extends HttpServiceException {\n"
        "  NoInternetException(Map<String, dynamic> body) : super(\"NO_INTERNET\", body);\n"
        "}\n"
        "\n"
        "class ServerException extends HttpServiceException {\n"
        "  ServerException(Map<String, dynamic> body) : super(\"SERVER_ERROR\", body);\n"
        "}\n"
        "\n"
        "class BadRequestException extends HttpServiceException {\n"
        "  BadRequestException(Map<String, dynamic> body, this.statusCode) : super(\"CLIENT_ERROR\", body);\n"
        "\n"
        "  final int statusCode;\n"
        "}\n"
        "\n"
        "class UnauthorizedException extends HttpServiceException {\n"
        "  UnauthorizedException(Map<String, dynamic> body) : super(\"UNAUTHORIZED\", body);\n"
        "}\n"
        "\n"
        "class ForbiddenException extends HttpServiceException {\n"
        "  ForbiddenException(Map<String, dynamic> body) : super(\"FORBIDDEN\", body);\n"
        "}\n"
        "\n"
        "class InternalRequestException extends HttpServiceException {\n"
        "  InternalRequestException(Map<String, dynamic> body) : super(\"INTERNAL_ERROR\", body);\n"
        "}\n"
    )


def get_hive_service_template() -> str:
    return (
        "import 'package:hive_ce_flutter/hive_flutter.dart';\n"
        "\n"
        "mixin class HiveService {\n"
        "  Future<Box> getBox(String boxName) async {\n"
        "    if (Hive.isBoxOpen(boxName)) {\n"
        "      return Hive.box(boxName);\n"
        "    }\n"
        "    return await Hive.openBox(boxName);\n"
        "  }\n"
        "\n"
        "  Future<void> closeBox(String boxName) async {\n"
        "    if (!Hive.isBoxOpen(boxName)) return;\n"
        "    await Hive.box(boxName).close();\n"
        "  }\n"
        "}\n"
    )
